$defs:
  int:
    $anchor: Int
    description: "A document that holds an integer"
    type: object
    properties:
      Key: { type: string }
      Int: { type: integer }
    required: [Key, Int]

  string:
    $anchor: String
    description: "A document that holds a string"
    type: object
    properties:
      Key: { type: string }
      String: { type: string }
    required: [Key, String]

  summer:
    $anchor: Summer
    type: object
    reduce: { strategy: merge }
    properties:
      Key: { type: string }
      Sum:
        type: integer
        reduce: { strategy: sum }
    required: [Key]

  joinRegister:
    $anchor: JoinRegister
    description: "Register document for join examples"
    type: object
    reduce: { strategy: merge }
    properties:
      LHS:
        type: integer
        reduce: { strategy: sum }
      RHS:
        type: array
        items: { type: string }
        reduce: { strategy: append }

  joinResult:
    $anchor: JoinResult
    description: "Output document for join examples"
    type: object
    properties:
      LHS: { type: integer }
      RHS: { type: array }
      Key: { type: string }
    required: [Key]
